### ISSUE TITLE
Support for Visual Studio 2017

### ISSUE THREAD

**Issue by DavidSimner** [GoEddie/tSQLt-TestAdapter#2]
Visual Studio 2017 now has a Release Candidate, with a public download at https://www.visualstudio.com/vs/visual-studio-2017-rc/

Can you support it please? :)  Thanks!

**Comment by GoEddie** [comment]
I'm going to wait for the RTM version, sorry - when it RTM's then I will upgrade it but I am a bit too busy at the moment.

**Comment by GoEddie** [comment]
https://github.com/GoEddie/tSQLt-TestAdapter/releases/tag/vs2017-beta

Note that this breaks vs 2015 on my machine so if you need to keep that then I would hold off until I have it working in both versions.

**Comment by way0utwest** [comment]
I downloaded the 2017 adapter, but it doesn't seem to discover any tests. The build works, and I have the runsettings pointed to my database. Any logging or other items I can check?

**Comment by GoEddie** [comment]
Hi Steve - try adding this to the run settings file:

<Parameter name="tSQLt-TestAdapter-Debug" value="true" />

The "Test" drop down of the output tab should show more details.

If you have a sample project that repro's it add it here and i'll take a look.


ed

**Comment by way0utwest** [comment]
Getting a virus alert when you send the .zip

**Comment by way0utwest** [comment]
I've been following this, which worked in VS 2015: https://documentation.red-gate.com/display/RR1/Tutorial%3A+Running+tests+in+Readyroll+with+tSQLt+Adapter

With the new adapter, once I got this from the output:
------ Discover test started ------
No RunSettings TestDatabaseConnectionString set - will not attempt to discover tests..
========== Discover test finished: 0 found (0:00:00.0065193) =========


This seems to be the case when the .runsettings is in the solution root. Is that not allowed?

**Comment by GoEddie** [comment]
The runsettings file has to be in the solution directory tree, that is a visual studio thing rather than this specific adapter. It looks like it can't find the runsettings file, is it definetly selected and it has a valid connection string?



ed


________________________________

**Comment by way0utwest** [comment]
Some answers here: https://voiceofthedba.com/2017/03/13/getting-the-tsqlt-run-adapter-working-in-visual-studio-2017/

Valid path to the database.

**Comment by GoEddie** [comment]
I can't see in the screen shot of the solution, are the tests in a folder with "Tests" in the name or the migrations directory?

There is an "Includes" in the runsettings so only tests in a path that matches *Tests* should be found.

Ed


________________________________

**Comment by way0utwest** [comment]
Ah, the name of the file matters here. That wasn't quite clear from the post you first made.  I updated the post, and having "tests" in the name worked here. Will play more.

**Comment by GoEddie** [comment]
Cool I'll update the docs and I'll put a couple of demo projects (ssdt/readyroll etc) when I get a chance.

Ed


________________________________

**Comment by way0utwest** [comment]
What’s this?

Here’s a sample project. One with the main project, one is a test project.

**Comment by GoEddie** [comment]
This works in vs 2017 now

**Comment by Narullah7** [comment]
Hi Eddie,

My tSQLt tests appear in test explorer however they pass even when I deliberately make them fail, I've tried this in VS 2017 and VS2015 but I get the same result. Please help.

p.s I make the tests fail with "tSQLt.Fail", 

**** Quick update
I've managed to make the test fail with the correct failure message e.g. AssertEquals, but it works in a really weird way, I make the tSQLt tests in SSMS, then in my tests project on VS, I do a schema compare and only add the schema if I made a new test class and the test cases (Procedures). 

However when I edit the tests in VS e.g. modify it to make it pass or fail, This doesn't do anything to the test in the test explorer. Am I doing something wrong.
